#include <stdint.h>
#include "color.h"
#include <string.h>
#include "videoDriver.h"
#include "lib.h"
#include "moduleLoader.h"
#include "naiveConsole.h"
#include "idtLoader.h"
#include "keyboard.h"
#include "libraryC.h"
